#!/usr/bin/python
#
# Parsing script for PAX/grsec log events
# Rickard Andersson <rickard@0x539.se>

import sys
import re

rx_pax   = "PAX:"
rx_grsec = "grsec:"

first    = True

for line in sys.stdin.readlines():

	if ( re.search( rx_pax, line ) ):

		if ( first ):
			print "grsec/PAX events:"
			first = False

		print "   " + line,

	elif ( re.search( rx_grsec, line ) ):

		if ( first ):
			print "grsec/PAX events:"
			first = False

		print "   " + line,
